"""Add OpenAI Vision analysis fields to complaint attachments

Revision ID: 000f4c9c67dd
Revises: 7450ef5c0424
Create Date: 2026-06-24 15:06:54.075535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000f4c9c67dd'
down_revision: Union[str, Sequence[str], None] = '7450ef5c0424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint_attachments', sa.Column('image_category', sa.String(length=100), nullable=True))
    op.add_column('complaint_attachments', sa.Column('detected_objects', sa.JSON(), nullable=True))
    op.add_column('complaint_attachments', sa.Column('danger_level', sa.String(length=50), nullable=True))
    op.add_column('complaint_attachments', sa.Column('image_description', sa.Text(), nullable=True))
    op.add_column('complaint_attachments', sa.Column('photo_based_category_hint', sa.String(length=100), nullable=True))
    op.add_column('complaint_attachments', sa.Column('recommended_action', sa.Text(), nullable=True))
    op.alter_column('complaints', 'ai_keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('reports', 'statistics_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'statistics_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('complaints', 'ai_keywords',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('complaint_attachments', 'recommended_action')
    op.drop_column('complaint_attachments', 'photo_based_category_hint')
    op.drop_column('complaint_attachments', 'image_description')
    op.drop_column('complaint_attachments', 'danger_level')
    op.drop_column('complaint_attachments', 'detected_objects')
    op.drop_column('complaint_attachments', 'image_category')
    # ### end Alembic commands ###
