"""Add GPS and AI analysis detailed fields to complaints

Revision ID: 7450ef5c0424
Revises: 9aac4fa4eeb5
Create Date: 2026-06-24 13:41:37.081044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7450ef5c0424'
down_revision: Union[str, Sequence[str], None] = '9aac4fa4eeb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('complaints', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('complaints', sa.Column('ai_category', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('ai_subcategory', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('ai_sentiment', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('ai_urgency', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('ai_sensitive', sa.Boolean(), nullable=False))
    op.add_column('complaints', sa.Column('ai_risk_type', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('ai_department', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('ai_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('complaints', sa.Column('ai_expected_days', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('ai_recommended_action', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'ai_recommended_action')
    op.drop_column('complaints', 'ai_expected_days')
    op.drop_column('complaints', 'ai_keywords')
    op.drop_column('complaints', 'ai_summary')
    op.drop_column('complaints', 'ai_department')
    op.drop_column('complaints', 'ai_risk_type')
    op.drop_column('complaints', 'ai_sensitive')
    op.drop_column('complaints', 'ai_urgency')
    op.drop_column('complaints', 'ai_sentiment')
    op.drop_column('complaints', 'ai_subcategory')
    op.drop_column('complaints', 'ai_category')
    op.drop_column('complaints', 'longitude')
    op.drop_column('complaints', 'latitude')
    # ### end Alembic commands ###
